blueprint:
  name: "plate01 p[x].b[y] displays the current weather condition"
  description: "A HASP button displays the current weather condition"
  source_url: "https://github.com/aderusha/HASwitchPlate/blob/dev/Home_Assistant/blueprints/automation/hasp_Display_Weather_Condition.yaml"
  domain: automation
  input:
    haspconnected:
      name: "HASP Device"
      description: "Select the HASP device"
      selector:
        entity:
          integration: mqtt
          domain: binary_sensor
          device_class: connectivity
    hasppage:
      name: "HASP Page"
      description: "Select the HASP page (1-11) for the weather condition"
      selector:
        number:
          min: 1
          max: 11
          mode: box
    haspbutton:
      name: "HASP Button"
      description: "Select the HASP button (4-15) for the weather condition.  Refer to the object map in the HASP documentation."
      selector:
        number:
          min: 4
          max: 15
          mode: box
    weather_provider:
      name: "Weather provider"
      description: "Select the weather provider to obtain the weather condition"
      selector:
        entity:
          domain: weather
    font:
      name: "Weather Condition Font"
      description: "Select the font for the weather condition:"
      selector:
        number:
          min: 0
          max: 10
          mode: box
    xcen:
      name: Text horizontal alignment
      description: "Horizontal text alignment 0:Left 1:Center 2:Right"
      selector:
        number:
          min: 0
          max: 2
          mode: box
    ycen:
      name: Text vertical alignment
      description: "Vertical text alignment 0:Top 1:Center 2:Bottom"
      selector:
        number:
          min: 0
          max: 2
          mode: box

mode: single
max_exceeded: silent

variables:
  haspconnected: !input haspconnected
  haspname: '{{ haspconnected.split(".")[1].split("_connected")[0] }}'
  hasppage: !input hasppage
  haspbutton: !input haspbutton
  weather_provider: !input weather_provider
  font: !input font
  xcen: !input xcen
  ycen: !input ycen
  haspobject: '{{ "p[" ~ hasppage ~ "].b[" ~ haspbutton ~ "]" }}'
  commandtopic: '{{ "hasp/" ~ haspname ~ "/command/" ~ haspobject }}'
  jsoncommandtopic: '{{ "hasp/" ~ haspname ~ "/command/json" }}'
  weather_condition: '{{states(weather_provider)|replace("windy-variant","windy")|replace("partlycloudy","partly cloudy")|title}}'

trigger:
  - platform: state
    entity_id: !input haspconnected
    to: "on"
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: !input weather_provider

condition:
  - condition: state
    entity_id: !input haspconnected
    state: "on"

action:
  - choose:
      # Update weather_condition if our weather provider changed state
      - conditions:
          - condition: template
            value_template: '{{ (trigger.platform == "state") and (trigger.entity_id == weather_provider) }}'
        sequence:
          - service: mqtt.publish
            data_template:
              topic: "{{commandtopic}}.txt"
              payload: '"{{weather_condition}}"'
    # Otherwise, apply the font+temp to the button
    default:
      - service: mqtt.publish
        data_template:
          topic: "{{jsoncommandtopic}}"
          payload: '["{{haspobject}}.font={{font}}","{{haspobject}}.xcen={{xcen}}","{{haspobject}}.ycen={{ycen}}","{{haspobject}}.txt=\"{{weather_condition}}\""]'

