blueprint:
  name: "plate01 Theme Dark on Light"
  description: "Press EXECUTE to apply the theme Dark on Light to the selected HASP device"
  source_url: "https://github.com/aderusha/HASwitchPlate/blob/dev/Home_Assistant/blueprints/automation/hasp_Theme_Dark_on_Light.yaml"
  domain: automation
  input:
    haspconnected:
      name: "HASP Device"
      description: "Select the HASP device"
      selector:
        entity:
          integration: mqtt
          domain: binary_sensor
          device_class: connectivity

mode: parallel
max_exceeded: silent

variables:
  haspconnected: !input haspconnected
  haspname: '{{ haspconnected.split(".")[1].split("_connected")[0] }}'
  selected_foreground_brightness: "1"
  selected_foreground_color: "[255, 255, 255]"
  selected_background_brightness: "255"
  selected_background_color: "[255, 255, 255]"
  unselected_foreground_brightness: "224"
  unselected_foreground_color: "[255, 255, 255]"
  unselected_background_brightness: "96"
  unselected_background_color: "[255, 255, 255]"

trigger: []

action:
  - service: light.turn_on
    data_template:
      entity_id: "light.{{haspname}}_selected_foreground_color"
      rgb_color: "{{selected_foreground_color}}"
  - service: light.turn_on
    data_template:
      entity_id: "light.{{haspname}}_selected_foreground_color"
      brightness: "{{selected_foreground_brightness}}"
  - service: light.turn_on
    data_template:
      entity_id: "light.{{haspname}}_selected_background_color"
      rgb_color: "{{selected_background_color}}"
  - service: light.turn_on
    data_template:
      entity_id: "light.{{haspname}}_selected_background_color"
      brightness: "{{selected_background_brightness}}"
  - service: light.turn_on
    data_template:
      entity_id: "light.{{haspname}}_unselected_foreground_color"
      rgb_color: "{{unselected_foreground_color}}"
  - service: light.turn_on
    data_template:
      entity_id: "light.{{haspname}}_unselected_foreground_color"
      brightness: "{{unselected_foreground_brightness}}"
  - service: light.turn_on
    data_template:
      entity_id: "light.{{haspname}}_unselected_background_color"
      rgb_color: "{{unselected_background_color}}"
  - service: light.turn_on
    data_template:
      entity_id: "light.{{haspname}}_unselected_background_color"
      brightness: "{{unselected_background_brightness}}"

